### ISSUE TITLE
stulpelis Iš eilės/be eilės 

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#10]
Iš eilės/be eilės - atrodo visiškai random laukas. Pvz priimant dvynius be eilės, užkalta kad iš eilės ir tt. Gal tada visai jo nereikia, jei jame nėra teisingos info. O info teisingos nebus, jei kažkas ranka tą lauką pildo.

**Comment by emiestas** [comment]
Uzregistruota programuotojams, ištaisysim, duomenų išrankos klaidas

On 18 May 2017, at 22:38, DovileJ <notifications@github.com<mailto:notifications@github.com>> wrote:


Iš eilės/be eilės - atrodo visiškai random laukas. Pvz priimant dvynius be eilės, užkalta kad iš eilės ir tt. Gal tada visai jo nereikia, jei jame nėra teisingos info. O info teisingos nebus, jei kažkas ranka tą lauką pildo.

**Comment by rokasSL** [comment]
Labai įdomu ar jau yra koks nors sprendimas? Nes vis dar dvynukai sudėti į bendrą eilę. 
Galiausiai jeigu kas dabar stovi eilėje pirmi, o bendroje eilėje (per vidurį) yra dvynukai, tai teveliai stovintis dabar pirmoje vietoje liks nusivylę.

**Comment by emiestas** [comment]
Reiktų patikrinti, gal perkėlimui laukia. Koks ID?



Labai įdomu ar jau yra koks nors sprendimas? Nes vis dar dvynukai sudėti į bendrą eilę.
Galiausiai jeigu kas dabar stovi eilėje pirmi, o bendroje eilėje (per vidurį) yra dvynukai, tai teveliai stovintis dabar pirmoje vietoje liks nusivylę.

**Comment by rokasSL** [comment]
O galit paaiskinti, ką reiškia "perkelimui laukia"?
konkreciai apie dvynukus 1281660740 ir 6351794265.

**Comment by emiestas** [comment]
Tūrėjau mintyje lanko įstaiga ir paraše prašymą perkelti į kitą įstaigą.
Konkrečiai šiuo atveju jie laukia eilėje, nes toje Įstaigoje nėra tiek vietų (pagal sistemoje suvesta informacija).

**Comment by rokasSL** [comment]
Bet pagal patvirtntas taisykles dvynukai neturėtų laukti eilėje, nes jie yra priimami be eilės. Tai logiką sako, kad sistema juos turėtų automatu dėti į pirmą eilės sąrašo vietą, prie visus kitus prioritetus.
