### ISSUE TITLE
kas buvo 05.18d

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#11]
Kas buvo 05.18d su šiais? Kai jie lankė tuo pačius darželius, ir buvo pasirašę sutartis. O tada atsirado 
Priskirtas į įstaigą: 2017-05-18
Sutartis pasirašyta: Sutartis nepasirašyta
6572832247
4747481676
83027842354
2096874518
6190642132
76643778833
99919425286
6095020718
8625382465
2087083722
19782508652
52142182972
8015495924
2043405414
37612987791
1680275369
2711819539
3967999408
88565114332
1151128660
1236147310
1297637335
9958821769
10694830733
2115818836
1545826200
7693754457
5099997904
8122944228
7356168681
29477668697
1411083263
64706392096
53384267657
79080758672
15500820772
1021284696
1485565125
97778827111
1179402963
50945174424
1836977341
60480768923
8870465478
1371469574
1822130260
1153455356
1202154135
20794781914
67951758325
1682748852
81648325534
38137368394
40744700561
43342043904
1690268842
2482436192
6004379115
17534618616
88989814775
86763862813
1118997229
1419958176
1941428466
2334342995
5558584030
1096499939
71922426195
44550415824
20920553773
1319540676
1598234416
5159962168
1542147528
78293798850
1910653135
76463522285
37668723739

**Comment by atvirasvilnius** [comment]
Yra keli atvejai šie vaikai kažkada lanke tą įstaiga. Išrankioje iš publikuotos pirmosios datos, pataisyta dabar kad į ataskaita dėtu veliausia datą
