### ISSUE TITLE
darzeliai_grupes.csv laisvos vietos

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#14]
Kodėl darzeliai_grupes.csv, paskutinis skaičius Free_Space, rodo laisvas vietas nemažai darželių, kur tų vietų tikrai nėra?

**Comment by atvirasvilnius** [comment]
Pertvarkyta ataskaita

**Comment by DovileJ** [comment]
Gal tą vieną dieną ir gerai rodė, o šiandien.. Iš kur tiek laisvų vietų atsirado? Paskutinis skaičius - kiek šiandiena laisvų, priešpaskutinis (0), kiek buvo prieš savaitę laisvų vietų.
ColiukėNuo 1,5 iki 3 metųLietuvių	0	6
ColiukėNuo 1 iki 2 metųLietuvių	0	7
DelfinukasNuo 1,5 iki 3 metųLietuvių	0	17
DelfinukasNuo 4 iki 5 metųLietuvių	0	10
GervelėNuo 1,5 iki 3 metųLietuvių	0	10
GervelėNuo 3 iki 7 metųRusų	0	7
GervelėNuo 3 iki 4 metųLietuvių	0	12
KrivūlėNuo 1,5 iki 3 metųLietuvių	0	15
KrivūlėNuo 3 iki 4 metųLietuvių	0	19
KrivūlėNuo 2 iki 6 metųLietuvių	0	6
KlevelisNuo 1,5 iki 3 metųRusų	0	16
KurpaitėNuo 1,5 iki 3 metųRusų	0	13
LašelisNuo 1,5 iki 3 metųRusų	0	8
LinelisNuo 1,5 iki 3 metųLietuvių	0	15
MarkučiaiNuo 3 iki 4 metųLietuvių	0	6
PagrandukasNuo 1,5 iki 3 metųLietuvių	0	18
PagrandukasNuo 3 iki 4 metųLietuvių	0	8
PagrandukasNuo 3 iki 6 metųLietuvių	0	7
PapartisNuo 1,5 iki 3 metųLietuvių	0	24
PapartisNuo 3 iki 4 metųLietuvių	0	22
PaslaptisNuo 1,5 iki 3 metųRusų	0	13
PumpurėlisNuo 3 iki 4 metųLietuvių	0	15
PumpurėlisNuo 4 iki 5 metųLietuvių	0	7
PumpurėlisNuo 6 iki 7 metųLietuvių	0	10
PušaitėNuo 1,5 iki 3 metųLietuvių	0	63
PušaitėNuo 3 iki 5 metųLietuvių	0	20
RaktelisNuo 1,5 iki 3 metųRusų	0	17
RaktelisNuo 1,5 iki 3 metųLenkų	0	32
RaktelisNuo 3 iki 4 metųLenkų	0	5
RaktelisNuo 3 iki 5 metųRusų	0	5
SakalėlisNuo 1,5 iki 3 metųLietuvių	0	30
SakalėlisNuo 3 iki 4 metųLietuvių	0	6
SakalėlisNuo 3 iki 6 metųLietuvių	0	5
ŠypsenaNuo 1,5 iki 3 metųLenkų	0	30
UžupiukasNuo 1,5 iki 3 metųLietuvių	0	16
UžupiukasNuo 3 iki 4 metųLietuvių	0	44
VėrinėlisNuo 1,5 iki 3 metųLietuvių	0	18
VėrinėlisNuo 1,5 iki 3 metųRusų	0	19
VėrinėlisNuo 3 iki 4 metųRusų	0	8
VoveraitėNuo 1,5 iki 3 metųLietuvių	0	36
ŽemynaNuo 1,5 iki 3 metųLietuvių	0	33
ŽemynaNuo 3 iki 4 metųLietuvių	0	10
ŽemynaNuo 4 iki 5 metųLietuvių	0	12
ŽemynaNuo 6 iki 7 metųLietuvių	0	10
ŽolynėlisNuo 1,5 iki 3 metųLietuvių	0	18
ŽolynėlisNuo 5 iki 6 metųLietuvių	0	20
VaivorykštėNuo 6 iki 7 metųRusų	0	10
SpygliukasNuo 1,5 iki 3 metųLietuvių	0	33
ŠaltinėlisNuo 1,5 iki 3 metųLenkų	0	10
Naujųjų verkiųNuo 1,5 iki 3 metųRusų	0	6
VolungėNuo 1,5 iki 3 metųLietuvių	0	16
