### ISSUE TITLE
darzeliai_grupes2.csv

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#15]
Gal gali ši ataskaita kas dieną atsinaujinti automatiškai? darzeliai_grupes2.csv

**Comment by atvirasvilnius** [comment]
O šita ataskaita netinka?
https://github.com/vilnius/darzeliai/blob/master/data/darzeliai_grupes.csv

**Comment by DovileJ** [comment]
Tinka tinka, tada ta grupes2 turėjo daug daugiau info, bet paskui buvo ir papildoma info sudėta į tą kasdien atsinaujinančią ataskaitą, viskas liuks dabar :)

**Comment by atvirasvilnius** [comment]
OK, jei reiktu papildomai info informuokite
