### ISSUE TITLE
Kodėl darzeliai_grupes.csv dingo pusė įstaigų?

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#17]
Kodėl darzeliai_grupes.csv dingo pusė įstaigų? Liko tik 80, kai buvo dvigubai daugiau.

**Comment by DovileJ** [comment]
Buvo 175 įstaigos 06.12d.

**Comment by atvirasvilnius** [comment]
Patikrinkite dabar,

**Comment by DovileJ** [comment]
Oi, šitas man atrodo jau senai pataisytas buvo :) viskas ok.
