### ISSUE TITLE
Nepasirašytos sutartys - 2476 vaikai?

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#18]
lankanciu_vaiku_ataskaita_pagal_grupes.csv - yra 2476 vaikai, su užrašu "Sutartis nepasirašyta". Čia tiek laisvų vietų tuos bus perdalinta? Ar skaičius tikrai teisingas - manau logiška jei būtų kelis k. mažesnis. Patikrinkit.

**Comment by DovileJ** [comment]
Šiandien sutartis nepasirašyta, rodo 1993 vaikus. Čia realu?

**Comment by emiestas** [comment]
ne, klaidingi duomenys, kuris čia duomenų rinkinys?

**Comment by DovileJ** [comment]
Abu kartus apie tą patį, šitą žiūriu: https://github.com/vilnius/darzeliai/blob/master/data/lankanciu_vaiku_ataskaita_pagal_grupes.csv
