### ISSUE TITLE
Laukiantys pasikeisti darželį

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#19]
Kur yra atvaizduojami laukiantys pasikeisti darželį? Ar jie matosi šioje eilėje? https://github.com/vilnius/darzeliai/blob/master/data/laukianciuju_eileje_ataskaita.csv
Kaip pažymimi / išskiriami tie, kurie laukia keitimui?

**Comment by DovileJ** [comment]
Tai kaip čia šitas klausimas?

**Comment by atvirasvilnius** [comment]
pridėjome stulpelį

**Comment by DovileJ** [comment]
Viskas puikiai, super, ačiūū!!!

**Comment by DovileJ** [comment]
Nors žinokit, vis dėlto, klausimas. Prašymo tipas "0" yra 2 vaikai, kas jie?
Prašymo tipas "2" - yra laukiantys pakeisti? 806 vaikai, taip?
Tada lankančių sąraše, šitame: https://github.com/vilnius/darzeliai/blob/master/data/lankanciu_vaiku_ataskaita_pagal_grupes.csv
paskutinis stulpelis yra laukiantys pakeisti darželį: Taip/ne. Sulyginus su eile, neatitinka skaičiai, nes šiame 
sąraše jau tik 647 vaikai, laukiantys pakeisti darželį.
neatitinka šie ID, ir daug daugiau ID

Vaiko   Identifikacinis Nr.
--
9440600785
21764273722
1099216923
5156604077
6561536457
8875479631
9516852657
1541276266
6709551046
49268076669
1624125024
5900623823
17254955427
2539596633

**Comment by emiestas** [comment]
Peržiūrėjome prašymų ID, čia ne šių metu prašymai, o kitiems metams.

**Comment by DovileJ** [comment]
Sakykim ID
21764273722

Šiuo metu lanko Coliukė

Ir laukia kaip normalus prašymas, o ne keitimas
Prašymo tipas - 1
Lankymo data 2017-09-01
1 pasirinktas   darželis
Paslaptis
2 pasirinktas   darželis
Saulėtekis
ir tt
