### ISSUE TITLE
Istoriniai duomenys

### ISSUE THREAD

**Issue by sirex** [vilnius/darzeliai#2]
Šiuo metu lentelėje `laukianciuju_eileje_ataskaita.csv` pateikiami tik einamieji duomenys iš kurių galima matyti kiek _šiuo metu_ yra vaikų eilėje laukiančių darželio.

`laukianciuju_eileje_ataskaita.csv` yra išvestiniai, t.y. juos nesunkiai galima gauti turint prašymo pateikimo ir sutarties pasirašymo datas, filtruojant tik tuos įrašus, kur prašymas dar nepasirašytas.

Turint istorinius duomenis, su prašymo pateikimo ir sutarties pasirašymo datomis, būtų galima gauti duomenis apie eilėje laukiančių vaikų skaičių, bet kuriuo metu, ne tik einamuoju.

Būt labai gerai, jei pateiktumėte istorinius duomenis, tada jų panaudojimo galimybės žymiai prasiplėstų.

**Comment by sirex** [comment]
> @povilasp rašė:
> padarysim kitą savaitę manau vėliausiai

Kita savaitė baigiasi gegužės 29 d.

**Comment by atvirasvilnius** [comment]
Prašymo pateikimo data yra laukianciuju_eileje_ataskaita.csv, pasirasymo sutartiues data yra Lankanciu csv. faile. Galima surišti per ID

**Comment by sirex** [comment]
Išbandžiau, nesigavo.

Bandžiau jungti `laukianciuju_eileje_ataskaita.csv` su `lankanciu_vaiku_ataskaita_pagal_grupes.csv` per `Vaiko Identifikacinis Nr.`. Po `inner` būdu sujungtų lentelių gavau tik 53 įrašus, kai jungiamose lentelėse buvo 34746 ir 9770 įrašai. Tai reiškia, kad abiejose lentelėse laukas `Vaiko Identifikacinis Nr.` turi skirtingą prasmę, arba kažkas negerai su duomenimis.

Arba aš darau kažką ne taip?

Jei teisingai supratau tavo komentarą, tai sujungus `laukianciuju_eileje_ataskaita.csv` ir `lankanciu_vaiku_ataskaita_pagal_grupes.csv` lenteles iš vienos `Prašymo pateikimo data` lauko gausiu, kada vaikas stojo į eilę, o iš kitos `Prašymo pateikimo data` lauko gausiu, kada jis pateko į darželį?

Tuo pačiu, dar vienas klausimas, ką tiksliai reiškia laukas `Lankymo data` iš `laukianciuju_eileje_ataskaita.csv` lentelės?

**Comment by atvirasvilnius** [comment]
Tuo pačiu, dar vienas klausimas, ką tiksliai reiškia laukas Lankymo data iš laukianciuju_eileje_ataskaita.csv lentelės?
"Lankymo data" - prašyme nurodyta nuo kada nori kad lankytų vaikas

ID turi sutapti, jei jis priskiairas darželiui tai su tuo pačiu ID keliauja

**Comment by sirex** [comment]
Dar kartą peržiūrėjau, [naujausius](https://github.com/vilnius/darzeliai/commit/fcd33c846ce5e373bd595fb25c4e5b10ad0fe79c) duomenis ir tikrai patvirtinu, kad `Vaiko Identifikacinis Nr.` nesutampa ir lentelės neapsijungia.

Pirmiausiai pabandžiau duomenis sujungti naudodamas [Pandas](http://pandas.pydata.org/):


```python
>>> import pandas as pd

>>> laukia = pd.read_csv('darzeliai/data/laukianciuju_eileje_ataskaita.csv', sep=';')

>>> lanko = pd.read_csv('darzeliai/data/lankanciu_vaiku_ataskaita_pagal_grupes.csv', sep=';')

>>> laukia['Vaiko Identifikacinis Nr.'].count()
9804

>>> lanko['Vaiko Identifikacinis Nr.'].count()
34762

>>> pd.merge(laukia, lanko, on='Vaiko Identifikacinis Nr.', how='inner').shape
(53, 76)

>>> pd.merge(laukia, lanko, on='Vaiko Identifikacinis Nr.', how='outer').shape
(44513, 76)
```

Tada dėl viso pikto pabandžiau duomenis įrašyti į SQLite duomenų bazę ir ten juos apjungti naudodamas SQL užklausą:

```python
>>> import sqlalchemy as sa

>>> engine = sa.create_engine('sqlite:////tmp/darzeliai.db')

>>> laukia.to_sql('laukia', engine)

>>> lanko.to_sql('lanko', engine)

>>> %load_ext sql

>>> %sql sqlite:////tmp/darzeliai.db

>>> %sql SELECT COUNT(*) FROM laukia INNER JOIN lanko USING ("Vaiko Identifikacinis Nr.")
[(53,)]
```

Bet gavau tą patį rezultatą, iš 9804 + 34762 įrašų sutampa tik 53.

Ar aš kažką netaip darau, ar vis dėl to yra klaida duomenyse?

**Comment by atvirasvilnius** [comment]
Tai gerai vadinasi nnuo to pullo buvo primti 53 vaikai. Paimkit laukianciuju_eileje_ataskaita.csv patimirma sucomitinta ir sujoininkite su snd dienai llankanciu vaiku sarasu

**Comment by sirex** [comment]
Klausimas, ar `laukianciuju_eileje_ataskaita.csv` yra pirminiai duomenys ar tiesiog ataskaita ištraukta kažkokiam tikslui iš pirminių duomenų?

Jei `laukianciuju_eiluje_ataskaita.csv` yra pirminiai duomenys, t.y. būtent savo duomenų bazėje nekaupiat istorinių duomenų (kas atrodytų kvailoka), tada matyt vienintelis kelias išgauti istorinius duomenis, išrenkant visas `laukianciuju_eiluje_ataskaita.csv` versijas iš git istorijos ir juos sujoinint.

Tačiau, jei vis tik pirminiuose duomenyse yra išsaugoti istoriniai duomenys, tai būtų nepalyginamai paprasčiau, jei skelbtumėte būtent pirminius, o ne išvestinius duomenis, iš kurių vienos užklausos pagalba būtų galima nesunkiai gauti ir `laukianciuju_eiluje_ataskaita.csv`.

**Comment by sirex** [comment]
@povilasp rašė, kad tai ko man reikia yra sukelta į `data/visi_prasymai.csv`, bandant užkrauti šį failą, gaunu klaidas 206-iuose įrašuose. Jei teisingai supratau, klaidos dėl to, kad kai kurie įrašai, turi papildomų stulpelių, kurie nėra apibrėžti pirmoje eilutėje. Kadangi nežinau, kad tie duomenys buvo ištraukti ar apjungti, sunku tiksliau nurodyti klaidų šaltinį. Gal galėtumėte pataisyti?

Daugiau informacijos: https://gist.github.com/sirex/40c40fb53a69f2a07e19f072630b02fe

**Comment by monrealis** [comment]
Man irgi nesutampa stulpelių skaičius. Įrašų kiekis pagal stulpelių skaičių `visi_prasymai.csv` dabartinėje versijoj
```
  67229 62
    196 72
      9 82
```

**Comment by emiestas** [comment]
Gal galite patikslinti klausimą?



[https://www.vilnius.lt/vilnius/m/m_images/wfiles/ixncam6884.png]

Pagarbiai

Jonas Pidkovas
Vilniaus m. savivaldybės administracijos
E. miesto departamento direktorius



Konstitucijos pr. 3–323 kab.
LT-09601 Vilnius
Tel. (8 5) 211 2745
El. paštas jonas.pidkovas@vilnius.lt<mailto:jonas.pidkovas@vilnius.lt>
http://www.vilnius.lt<https://url.serverdata.net/?ah4a1I7qKqcwW-qin17e7BJQfPN_pd66MbUV_s9sfUaw~>

**Comment by monrealis** [comment]
https://github.com/vilnius/darzeliai/blob/7e6fcc0e138dfd2440357f1d36dd8deafa125e56/data/visi_prasymai.csv faile yra nevienodas stulpelių skaičius eilutėse. Turėtų būti visur po 62 stulpelius, bet yra eilučių, kuriose yra 72 ir 82 stulpeliai.
