### ISSUE TITLE
lankomumo_ziniarasciai_2017-09-01-2017-09-30.csv

### ISSUE THREAD

**Issue by billtallman** [vilnius/darzeliai#20]
Lankomumo žiniaraščiuose nepilni duomenys.
Tikriausiai reikia atnaujinti, matyt nebuvo įvesti į sistemą lauku.

**Comment by atvirasvilnius** [comment]
Gal galite patikslinti?

**Comment by billtallman** [comment]
Mano sūnus lanko Eglutės darželį. Tiek rugsėjo mėn, tiek spalio mėnesiais lankomumo žiniaraštis šiam darželiui minimalus, t.y. stipriai trūksta informacijos, nurodytos tik kelios grupės iš viso darželio.
Lapkričio mėnesį informacijos daugiau, jau arčiau tiesos.
Jeigu informacija iš darželio buvo pateikta pavėluotai, matyt reikėtų žiniaraščius sugeneruoti iš naujo.

**Comment by emiestas** [comment]
Pavėlinome duomenų atnaujinimą, nes darželiai ne visas grupes spėdavo suvesti į tabelį. Dabar turėtų būti gerai.

**Comment by billtallman** [comment]
Labai gerai, ar galima atnaujinti visus duomenis nuo Rugsėjo?
Ačiū

**Comment by emiestas** [comment]
done



[ziemav02]

Pagarbiai

Jonas Pidkovas
Vilniaus m. savivaldybės administracijos
E. miesto departamento direktorius



Konstitucijos pr. 3–323 kab.
LT-09601 Vilnius
Tel. (8 5) 211 2745
El. paštas jonas.pidkovas@vilnius.lt<mailto:jonas.pidkovas@vilnius.lt>
http://www.vilnius.lt<https://url.serverdata.net/?ah4a1I7qKqcwW-qin17e7BJQfPN_pd66MbUV_s9sfUaw~>
