### ISSUE TITLE
Kur matosi kokie vaikai laukia darželio keitimui ir kur?

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#21]
Kur matosi, kokie vaikai ir kur laukia darželio keitimui? Kad matytųsi, jog vaikas ID toks anoks, iš darželio va toks, laukia ten ir ten. Kad būtų galima sujungti/ suporuoti?

**Comment by atvirasvilnius** [comment]
Pridėsime stulpelį šioje ataskaitoje:
https://github.com/vilnius/darzeliai/issues/19
