### ISSUE TITLE
Trinapolio darželis - duomenų tikslumas

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#22]
Ar verta lankančių vaikų sąraše skelbti Trinapolio duomenis, ten kai kuriose grupėse po 1 vaiką, - vistiek nėra teisybė, manau kažkokie duomenys suvesti prieš kelis metus ir likę. Taip pat, ir pernai buvo klausimų stojant į eiles, kad lyg leidžia pasirinkti Trinapolį, bet paskui savivaldybė ten vaikų neskirsto.

**Comment by emiestas** [comment]
Na grupėje daugiau vaikų yra. Mes skelbiame viską kas suvesta į sistemą, ar verta ar ne nesprendžiame.

[cid:image001.png@01D3742D.5FF92470]

**Comment by DovileJ** [comment]
Ok, supratau, čia ne Jūsų sritis, rašiau kad grupėse po mažai vaikų, ir tai nėra realu,
Kėkštukų | 2 vaikai
Ereliukų | 6 vaikai
Pingvinukai | 6
Vyturėlių | 8
Kregždučių | 11
Gandriukų | 11
NYKŠTUKŲ | 12
Gegužiukų | 13
Pelėdžiukų | 21
Galit trinti šį klausimą.

**Comment by atvirasvilnius** [comment]
pasitikrinkime
![image](https://user-images.githubusercontent.com/12123428/34030221-aad8c144-e174-11e7-9444-dcd5b0d0cb90.png)

**Comment by atvirasvilnius** [comment]
kaip ir viskas gerai

**Comment by DovileJ** [comment]
Tai sakau kad gerai, bet esmė, kad grupių po 2 vaikus realiai nėra darželyje, ir nė vieno vaiko 2017m į šį darželį nepriskirta, bet čia jau ne jūsų problema, o tų kas duomenis veda į sistemą, kad neatnaujina šio darželio info.
