### ISSUE TITLE
darzeliai_grupes.csv trūksta įstaigų

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#3]
darzeliai_grupes.csv trūksta įstaigų - jame yra tik 118 įstaigų, o prašymai į darželius yra priimami į 177 įstaigas, tai reikia kad būtų visos 177 įstaigos ir faile darzeliai_grupes.csv.

**Comment by atvirasvilnius** [comment]
Sveiki,
Patikrinkite dabar turėtų būti viskas gerai,
Ačiū už pastbėjimą

**Comment by DovileJ** [comment]
Dar trūksta darželio Lazdynėlis.

**Comment by emiestas** [comment]
Ačiū, už pastebėjimą suvestas taisyklingai adresas, Lazdynėlis tūrėti atsirasti automatiškai.

**Comment by DovileJ** [comment]
Darželio Žolynas dar pritrūkau ;)

**Comment by emiestas** [comment]
Done
Grižus programuotojui pakeisime išranka, nes pastebėjau jei ne tikslus adresas tai neima į atvirus duomenys Įstaigos duomenų



[https://www.vilnius.lt/vilnius/m/m_images/wfiles/ixncam6884.png]

Pagarbiai

Jonas Pidkovas
Vilniaus m. savivaldybės administracijos
E. miesto departamento direktorius



Konstitucijos pr. 3–323 kab.
LT-09601 Vilnius
Tel. (8 5) 211 2745
El. paštas jonas.pidkovas@vilnius.lt<mailto:jonas.pidkovas@vilnius.lt>
http://www.vilnius.lt<https://url.serverdata.net/?ah4a1I7qKqcwW-qin17e7BJQfPN_pd66MbUV_s9sfUaw~>
