### ISSUE TITLE
laukianciuju_eileje_ataskaita.csv darželių priskyrimai seniūnijoms

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#4]
Faile laukianciuju_eileje_ataskaita.csv, patikslinti laukus 1 pasirinktas darželis, 1 darželio Seniūnija (2-5 pasirinkimai/prioritetai analogiškai), nes yra klaidingai priskirtų darželių seniūnijoms. Pvz šie Žirmūnų - Šnipiškių darželiai priskirti Verkiams (Taip, Verkiams galioja pirmenybė Žirmūnų darželius, bet nuo to darželiai vistiek lieka Žirmūnų): Žirmūnėliai	Žirmūnų g. 13 
Rūta	Žirmūnų g. 50, Vilnius
Smalsučiai	Minties g. 40, Vilnius
Žvangutis	Rinktinės g. 38A - Šnipiškės?

**Comment by atvirasvilnius** [comment]
Yra darželių teritorinis suskirstymas, pagal tai darželiai suskirstyti.
https://www.e-tar.lt/portal/lt/legalAct/53ec3ff0e50011e4a4809231b4b55019/PCIzBVwHBH
Jus norite papildomo stulpelio, kurioje seniūnijoje randasi darželis?

**Comment by DovileJ** [comment]
Ne, nenoriu papildomo stulpelio. Tame įstatyme darželis Žirmūnėliai yra parašytas ir prie Žirmūnų, ir prie verkių seniūnijų - nes Žirmūnų darželiai priklauso ir Verkiams kaip pirmenybė. Taigi visi Žirmūnų darželiai suvesti įstatyme 2k - pasižiūrėkite. Bet tai, kad Žirmūnų darželis suvestas 2k, jis nepatampa Verkių seniūnijos darželiu, ar ne?

**Comment by DovileJ** [comment]
Manau teisingiausia visų rajonų visus darželius priskirt pagal http://www.vilnius.lt/index.php?460405890 , pagal seniūnijų ribas, ir tada ir taip aišku, kad Žirmūnų darželiai priklauso ir Verkiams. Kaip kad Karoliniškių darželiai priklauso ir Pilaitei ir pan.

**Comment by atvirasvilnius** [comment]
Darželis tvarkoje suvestas du kartus, nes jis pagal teritorija gali priklausyti daugiau nei vienai seniūnijai, šiuo atvejų faile matau, kad išvedama viena seniūnija, kuri žymima sistemoje pirma. Dar taip pat teritorijos yra pagal kalbas.
![image](https://cloud.githubusercontent.com/assets/12123428/25738756/8b3c18c4-3187-11e7-9238-a523dfbbbef0.png)

**Comment by DovileJ** [comment]
Tai padarykit kad faile  laukianciuju_eileje_ataskaita.csv 1 pasirinktas darželis, 1 darželio Seniūnija visi Žirmūnų darželiai ir būtų su pažymėjimu sistemoje "pirma". O dabar kas antras Žirmūnų yra kaip Žirmūnų, kas antras kaip Verkių ir tt. Ir analogiškai kitoms seniūnijoms, ar Jūs nesuprantate iš vis apie ką aš čia? Ar suprantate ką aš prašau pataisyti? Na kodėl Žirmūnėliai dabar Verkiams priskirti, jei ir įstatyme yra 2k minimi, ir jie randasi Žirmūnuose? Ir kodėl Spragtukas jau Žirmūnams priskirtams, nors irgi įstatyme 2k minimas? Kodėl jų priskyrimai skiriasi?

**Comment by atvirasvilnius** [comment]
Spragtukas dar sudėtingesnis, nes ten ugdosi vaikai ne tik LT kalba, pagal kalbas irgi kitos teritorijos:
![image](https://cloud.githubusercontent.com/assets/12123428/25742909/6f1ff17a-319a-11e7-9967-4a67642202a9.png)
Kaip suskirstyti darželio teritorijų priklausomybes tame pačiame faile :(
Gal atskirai padaryti įstaigų failą su teritorijų priklausomybėm?

**Comment by DovileJ** [comment]
Žiūrėkit. Viską esat programoje priskyrę gerai, ir programa veikia gera. BET gal galite tame faile atvaizduoti darželio seniūniją pagal darželio adresą? Juk adresas priklauso kažkokiai vienai seniūnijai, net jei darželis priklauso ir kelioms seniūnijoms, ar ne? Na jei as esu tėvas iš Žirmūnų, aš išsifiltravus Žirmūnų seniūnija noriu matyt Žirmūnų darželius. Ir man nė į galvą neateis dar Žirmūnų darželio Žirmūnų g adresu ieškot užsidėjus filtrą Verkiai. Ar Šnipiškės. Jei esu iš Verkių, as žinau, kad man priklauso Verkių, Žirmūnų ir Šnipiškių darželiai, todėl išsifiltravus šiuos tris rajonus, ir matysiu iš ko rinktis. Sudėkite prašau tą taškiuką (pagr) ant tos seniūnijos, kurios žemėje stovi darželis. O ne atsitiktine tvarka, nes matau jokio kito pagrindo tam nėra, ir buvo belenkaip sutapšnota tie pažymėjimai (pagr). Net nežinau kaip dar aiškiau paaiškinti.

**Comment by DovileJ** [comment]
Vis dar rodo klaidingai, gal galite pertaškuoti darželius, uždedant pagr. ant to teritorijų priskyrimo, kur stovi darželio pastatas??

**Comment by atvirasvilnius** [comment]
Taip palaipsniui tai atliksime, iš karto negalime to atlikti.

**Comment by DovileJ** [comment]
Žodis palaipsniui, reiškia niekada. Kodėl negalima peržiūrėti tų darželių ir pertaškuoti vienu metu? Gi ne vaikus, o darželius reikia patikrinti.
