### ISSUE TITLE
lankanciu_vaiku_ataskaita_pagal_grupes.csv

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#5]
lankanciu_vaiku_ataskaita_pagal_grupes.csv - nebėra lauko (stulpelio) "Vaiko priėmimo į grupę data", o anksčiau buvo. Gal galite vėl atgal pridėti? Tas stulpelis buvo pakeistas į "Sutartis pasirašyta", bet tai ne tas pats. Nes anksčiau buvo data, o dabar tik TAIP arba NE. Reikia kokios nors datos - arba priėmimo į grupę data, ar sutarties pasirašymo data ar ką nors pan - kad būtų lengva atskirti kuriais metais kurie vaikai priimti.

**Comment by atvirasvilnius** [comment]
Papildytas stulpelis vaiko priėmimo grupė data
