### ISSUE TITLE
lankanciu_vaiku_ataskaita_pagal_grupes.csv

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#6]
Sveiki, apie šį failą lankanciu_vaiku_ataskaita_pagal_grupes.csv
Gal galima įdėti lauką - vaikas registruotas Vilniaus mieste?
Jei nėra galimybės su pracheckinimu bent 2k per metus tos registracijos, tai bent ar priėmimo metu buvo registruotas Vilniuje, ar ne.

**Comment by DovileJ** [comment]
Ar jei "vaiko seniūnija" yra tuščias langelis, reiškia kad registruotas ne VLN? Bet ne, nes į tuščius laukus pakliūna ir ne vilniečiai, ir registruoti prie savivaldybės bendrai (be seniūnijos). Jei lauke "Vaiko seniūnija" pridėsit seniūnija pvz VISOS, kas reikštų kad registruotas Vilniaus mieste prie savivaldybės, ir blanks liks tik registruotiem prie kitų savivaldybių, irgi ok.

**Comment by emiestas** [comment]
Sveiki,

Pridėsime, tačiau tam reikės laiko, nes reikia. Patikrinkite man atrodo jei nėra sen., tai asmuo nedeklaruotas Vilniuje.

**Comment by DovileJ** [comment]
Jei nėra sen, tai taip, asmuo nedeklaruotas VLN. Bet kaip tada pasižymi deklaruoti VLN, bet be seniūnijos, o  prie savivaldybės? 
Pvz laukiančių eilėje ataskaita, yra 471 vaikas blank lauku - nedeklaruotas VLN, ir dar yra seniūnijos ne tik antakalnis, žirmūnai ir tt, bet ir "visos" - 1432 vaikai, kurie yra deklaruoti prie Vilniaus savivaldybės be konkrečios seniūnijos.

**Comment by emiestas** [comment]
Reikia dar ziureti, nes kai kuriu sen., nepriskiria sistema nes Vilniuje apie 4000 adresu nesutampa su gyventoju registro duomenimis.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Fri, May 12, 2017 at 9:56 AM +0300, "DovileJ" <notifications@github.com<mailto:notifications@github.com>> wrote:


Jei nėra sen, tai taip, asmuo nedeklaruotas VLN. Bet kaip tada pasižymi deklaruoti VLN, bet be seniūnijos, o prie savivaldybės?
Pvz laukiančių eilėje ataskaita, yra 471 vaikas blank lauku - nedeklaruotas VLN, ir dar yra seniūnijos ne tik antakalnis, žirmūnai ir tt, bet ir "visos" - 1432 vaikai, kurie yra deklaruoti prie Vilniaus savivaldybės be konkrečios seniūnijos.
