### ISSUE TITLE
Nuo kada šitie vaikai lanko darželius?

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#7]
Vaiko Identifikacinis Nr.
6131841699
7561763602
1341696594
87021308503
Stulpelis "Vaiko priėmimo į grupę data"

**Comment by atvirasvilnius** [comment]
6131841699 - 2016-06-01 16:35:13 Vaikas priskirtas į darželi, 2016-06-22 15:29:38 - uždėta varnele, kad sutartis pasirašyta

756176360220 - 16-12-05 14:30:07 Vaikas priskirtas į darželi, 

1341696594- 2016-06-01 16:35:13 Vaikas priskirtas į darželi. 2016-06-22 15:29:38 -Priskirimas į grupę Pasirašyta sutartis dėl vaiko " (lankymo darželį
