### ISSUE TITLE
600 vaikų pernai nepasirašė sutarčių

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#8]
kodėl 600 vaikų, 
laukas Vaiko priėmimo į grupę data - iki 2016m (imtinai)
+
"Sutartis nepasirašyta", vis dar faile lankanciu_vaiku_ataskaita_pagal_grupes.csv
Dar laukiat sutarčių?

**Comment by emiestas** [comment]
Sveiki,
Gal galite pvz. pateikti keletą ID

**Comment by DovileJ** [comment]
Iš priekio sąrašo:
2092431875
2760970218
4177753994
97667536161
2766357229
4882556718
5935579452
6308519574
8693750994
1578089280
2892553878
4013099670
19892724367
69893760439
1183272346
1756799209
2853616585
4917599786
5378885117
7979566741
8905075899
5706671963

**Comment by DovileJ** [comment]
Ir iš galo sąrašo:
7339575051
7599148364
8680773943
1165037225
2165675358
75822955421
92496791690
1113731535
3273127718
3362089746
4591550636
9201769624
1420929477
2083974132
2854877428
4339671951
8520589200
27840592998
40706531692
41745965224
66162315180
69095956441
90324652854
8444102065

**Comment by atvirasvilnius** [comment]
Iš ko sprendžiate, kad nepasirašyta? Atsitiktine tvarka peržiūrėjau sistemoje, kad pasirašytos sutartys

**Comment by DovileJ** [comment]
Pažiūrėjau pirmus penkis, visus meta kaip "sutartis nepasirašyta" faile lankanciu_vaiku_ataskaita_pagal_grupes.csv

**Comment by atvirasvilnius** [comment]
Ar dar likusi ši problema?

**Comment by DovileJ** [comment]
Taip... rodo kad 1003 vaikai nepasirašę sutarčių. Iš jų tik 103, kurie dar realiai gali būti nepasirašę, nes priskirti į grupes 2017m 11-12mėn. Kiti priskirti į grupes 2016m, 2015m arba visai be datų.. tų jau nebeturėtų būti. Nes jie arba lanko, arba 2 metus sutarties pasirašymo vistiek niekas nelaukia.

**Comment by DovileJ** [comment]
Stulpelis "Priskirtas į įstaigą" - turėtų imti kažkokią tai automatiškai šiandieninę datą, nes dabar yra tokių, kurie ale paskirti į grupes 2017.12.31, arba net 2018m., o pavasarį dalį vaikų priiminėjo ir buvo rodoma 2016m data, nors jau buvo 2017 metai. Patikrinkit, iš kur ima datą. Failas tas pats: https://raw.githubusercontent.com/vilnius/darzeliai/master/data/lankanciu_vaiku_ataskaita_pagal_grupes.csv
