### ISSUE TITLE
kaip čia 

### ISSUE THREAD

**Issue by DovileJ** [vilnius/darzeliai#9]
Kaip čia, jei priskirti į įstaigą 2015-2016m, o Vaiko priėmimo į grupę data
 nuo 2017?
Įrašai nauji, pakvietimai vaikams išsiųsti dabar. Arba priskirti 2017. sausį, prėmimo data rugsėjis-gruodis?
tokių viso 48 randu:
Vaiko Identifikacinis Nr.
8526813977
9635669748
6073970691
6138451393
2988856911
1031628633
4551111709
2191720088
3233000497
2514377385
4270513515
2723284353
4550819172
3031790547
8588753136
1799326151
2273629510
8281249701
5084307083
1020073382
2370778977
2414957010
1547117566
4427383755
2857591912
1558093905
9783450998
8383489040
8155080474
6712878938
9423458813
8518422934
1402200673
8045459660
1865253659
4976069028
7825266216
8069534610
8547544537
3769217717
4460061333
1256862463
9762417198
3278086723
3693328191
4481343085
4542365309

**Comment by atvirasvilnius** [comment]
Kelis peržiūrėjau, tai jie buvo priimti su kriterijais be eiles. pvz vienas Atžalėlės
2016-07-04 išbrauktas iš įstaigos, nes nepasirašyta sutartis. ir šiemet priimtas į Kaštoną su pirmumo kriterijumi be eiles. Tai lyg sutvarkome, kad čia išvestu aktualesne data.
